/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package De4;

import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Huong
 */
public class QuanLiSach extends javax.swing.JFrame {

    /**
     * Creates new form QuanLiSach
     */
    
    List<Sach> listSach = new ArrayList<>();
    DefaultTableModel model = new DefaultTableModel();
    int vitri;
    
    
    
    public QuanLiSach() {
        initComponents();
        model = (DefaultTableModel) tblSach.getModel();
        listSach.add(new Sach("a", "KHTN", "Mới", 10000));
        listSach.add(new Sach("b", "KHXH", "Cũ", 15000));
        listSach.add(new Sach("c", "KHTN", "Cũ", 5000));
        listSach.add(new Sach("d", "KHXH", "Mới", 1000));
        fill();
        if(listSach.size()>=1){
            vitri=0;
            display(vitri);
        }
        chayChu();
        chayMang();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lbChu = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        cbbLoai = new javax.swing.JComboBox<>();
        rdbMs = new javax.swing.JRadioButton();
        rdbCu = new javax.swing.JRadioButton();
        txtGia = new javax.swing.JTextField();
        btnGhi = new javax.swing.JButton();
        btnDoc = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnLoc = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnSxTen = new javax.swing.JButton();
        btnSxepGia = new javax.swing.JButton();
        lbDemTG = new javax.swing.JLabel();
        lbDH = new javax.swing.JLabel();
        btnThoat = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSach = new javax.swing.JTable();
        lblHang = new javax.swing.JLabel();
        lbMang = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbChu.setText("QUẢN LÍ SÁCH");

        jLabel2.setText("Tên sách");

        jLabel3.setText("Loại sách");

        jLabel4.setText("Hàng");

        jLabel5.setText("Giá");

        cbbLoai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "KHTN", "KHXH" }));

        buttonGroup1.add(rdbMs);
        rdbMs.setText("Mới");

        buttonGroup1.add(rdbCu);
        rdbCu.setText("Cũ");

        btnGhi.setText("Ghi");
        btnGhi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGhiActionPerformed(evt);
            }
        });

        btnDoc.setText("Đọc");
        btnDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnLoc.setText("Lọc");
        btnLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnSxTen.setText("Sx Tên");
        btnSxTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSxTenActionPerformed(evt);
            }
        });

        btnSxepGia.setText("Sx Giá");
        btnSxepGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSxepGiaActionPerformed(evt);
            }
        });

        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        tblSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Tên", "Loại", "Hàng", "Giá", "Đánh giá"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSachMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSach);

        lblHang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHang.setText("...");

        lbMang.setText("Lê Thị Hương");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(25, 25, 25)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel3)
                                                .addComponent(jLabel4)
                                                .addComponent(jLabel5))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(rdbMs)
                                                    .addGap(10, 10, 10)
                                                    .addComponent(rdbCu, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(cbbLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtGia)))))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(62, 62, 62)
                                    .addComponent(lbChu)))
                            .addGap(26, 26, 26)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnGhi, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lbDemTG, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                                    .addComponent(btnSxTen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnSxepGia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbDH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(lblHang, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbMang, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbChu)
                    .addComponent(lbDemTG, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                    .addComponent(lbDH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGhi)
                    .addComponent(btnUpdate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbbLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDoc)
                    .addComponent(btnSxTen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rdbMs)
                    .addComponent(rdbCu)
                    .addComponent(btnXoa)
                    .addComponent(btnSxepGia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnLoc)
                        .addComponent(btnThoat)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblHang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(lbMang))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void chayChu(){
        new Thread(){
            public void run(){
                String chu = lbChu.getText()+" ";
                while (true) {                   
                   lbChu.setText(chu);
                   chu=chu.substring(1,chu.length())+chu.charAt(0);
                    try {
                        Thread.sleep(1000);
                    } catch (Exception e) {
                    }
                }
            }
        }.start();
    }
    
    public void chayMang(){
        new Thread(){
            public void run(){
                while (true) {
                   String chu = lbMang.getText();
                   String[] mang = chu.split(" ");
                   chu = mang[1]+" "+mang[2]+" "+mang[0];
                   lbMang.setText(chu);
                    try {
                        Thread.sleep(1000);
                    } catch (Exception e) {
                    }
                }
            }
        }.start();
    }
    
    private void btnGhiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGhiActionPerformed
        // TODO add your handling code here:
        try {
            add();
            fill();
            luu();
            lblHang.setText((vitri+1)+"/"+listSach.size());
            lmMoi();
        } catch (Exception e) {
        }       
    }//GEN-LAST:event_btnGhiActionPerformed

    private void btnDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocActionPerformed
        // TODO add your handling code here:
        try {
            mo();
            if(listSach.size()>0){
                fill();
                vitri=0;
                display(vitri);
                tblSach.setRowSelectionInterval(vitri, vitri);
            }else{
                JOptionPane.showMessageDialog(rootPane, "danh sách trống");
            }
        } catch (Exception e) {
        }
        
    }//GEN-LAST:event_btnDocActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        xoa();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnLocActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSxTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSxTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSxTenActionPerformed

    private void btnSxepGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSxepGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSxepGiaActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        int chon = JOptionPane.showConfirmDialog(rootPane, "Thoát","Bạn muốn thoát k?",JOptionPane.YES_NO_OPTION);
        try {
            if(chon==JOptionPane.YES_OPTION){
            System.exit(0);
        }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Mời chọn");
        }
        
    }//GEN-LAST:event_btnThoatActionPerformed

    private void tblSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSachMouseClicked
        // TODO add your handling code here:
        int row = tblSach.getSelectedRow();
        
        if(row>=0){
            vitri=row;
            display(vitri);
        }
    }//GEN-LAST:event_tblSachMouseClicked

    public void lmMoi(){
        txtTen.setText("");
        cbbLoai.setSelectedItem("KHTN");
        rdbMs.setSelected(true);
        txtGia.setText("");
        vitri=-1;
    }
    
    public void add(){
        Sach s = new Sach();
        s.setTen(txtTen.getText());
        s.setLoai((String) cbbLoai.getSelectedItem());
        if(rdbMs.isSelected()==true){
            s.setHang("Mới");
        }else{
            s.setHang("Cũ");
        }
        s.setGia(Double.parseDouble(txtGia.getText()));
        listSach.add(s);
    }
    
    public void fill(){
        model.setRowCount(0);
        for(Sach x: listSach){
            model.addRow(new Object[]{x.getTen(),x.getLoai(),x.getHang(),x.getGia(),x.danhGia()});
        }
        display(vitri);
    }
    
    public void display(int vitri){
        if(vitri>=0){
            txtTen.setText(listSach.get(vitri).getTen()); 
            cbbLoai.setSelectedItem(listSach.get(vitri).getLoai());
            if(listSach.get(vitri).getHang().equalsIgnoreCase("Mới")){
                rdbMs.setSelected(true);
            }else{
                rdbCu.setSelected(true);
            }
            txtGia.setText(listSach.get(vitri).getGia()+"");  
            lblHang.setText((vitri+1)+"/"+listSach.size());
            tblSach.setRowSelectionInterval(vitri, vitri);
        }else{
            lblHang.setText("...");
        }
    }
    
    public void xoa(){
        vitri= tblSach.getSelectedRow();
        try {            
            listSach.remove(vitri);
            model.removeRow(vitri);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "chọn dóng xóa");
        }
    }
    
    public void luu(){
        try {
            ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream("sach.txt"));
            oos.writeObject(listSach);
            oos.flush();
            oos.close();
            JOptionPane.showMessageDialog(rootPane, "Lưu tc");
        } catch (Exception e) {
//            JOptionPane.showMessageDialog(rootPane, "Lưu thất bại");
        }       
    }
    
    public void mo(){
        try {
            ObjectInputStream ois = new ObjectInputStream(new FileInputStream("sach.txt"));
            listSach = (List<Sach>) ois.readObject();
            ois.close();
            fill();
            JOptionPane.showMessageDialog(rootPane, "Mở tc");
        } catch (Exception e) {
//            JOptionPane.showMessageDialog(rootPane, "Mở thất bại");
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLiSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLiSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLiSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLiSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLiSach().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDoc;
    private javax.swing.JButton btnGhi;
    private javax.swing.JButton btnLoc;
    private javax.swing.JButton btnSxTen;
    private javax.swing.JButton btnSxepGia;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbbLoai;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbChu;
    private javax.swing.JLabel lbDH;
    private javax.swing.JLabel lbDemTG;
    private javax.swing.JLabel lbMang;
    private javax.swing.JLabel lblHang;
    private javax.swing.JRadioButton rdbCu;
    private javax.swing.JRadioButton rdbMs;
    private javax.swing.JTable tblSach;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtTen;
    // End of variables declaration//GEN-END:variables
}
